### PR TITLE
Api v4 update

### PR DESCRIPTION
**Pull request by alibazlamit**
ProfitBricks API update to V4 features

```==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./profitbricks/ -v  -timeout 120m
=== RUN   TestAccDataSourceDatacenter_matching
--- PASS: TestAccDataSourceDatacenter_matching (14.48s)
=== RUN   TestAccDataSourceImage_basic
--- PASS: TestAccDataSourceImage_basic (9.13s)
=== RUN   TestAccDataSourceLocation_basic
--- PASS: TestAccDataSourceLocation_basic (1.26s)
=== RUN   TestAccResource_basic
--- PASS: TestAccResource_basic (15.31s)
=== RUN   TestProvider
--- PASS: TestProvider (0.00s)
=== RUN   TestProvider_impl
--- PASS: TestProvider_impl (0.00s)
=== RUN   TestAccProfitBricksDataCenter_Basic
--- PASS: TestAccProfitBricksDataCenter_Basic (19.25s)
=== RUN   TestAccProfitBricksFirewall_Basic
--- PASS: TestAccProfitBricksFirewall_Basic (349.78s)
=== RUN   TestAccProfitBricksGroup_Basic
--- PASS: TestAccProfitBricksGroup_Basic (13.62s)
=== RUN   TestAccProfitBricksIPBlock_Basic
--- PASS: TestAccProfitBricksIPBlock_Basic (3.00s)
=== RUN   TestAccProfitBricksLanIPFailover_Basic
--- PASS: TestAccProfitBricksLanIPFailover_Basic (251.80s)
=== RUN   TestAccProfitBricksLan_Basic
--- PASS: TestAccProfitBricksLan_Basic (50.20s)
=== RUN   TestAccProfitBricksLoadbalancer_Basic
--- FAIL: TestAccProfitBricksLoadbalancer_Basic (333.24s)
        testing.go:428: Step 0 error: After applying this step, the plan was not empty:

                DIFF:

                UPDATE: profitbricks_loadbalancer.example
                  ip: "10.10.124.225" => ""

                STATE:

                profitbricks_datacenter.foobar:
                  ID = eea5d0d7-69e9-44c0-88c5-77f052dc2ff6
                  description =
                  location = us/las
                  name = loadbalancer-test
                profitbricks_loadbalancer.example:
                  ID = a069d32b-5018-455b-88d2-5a72f4762ead
                  datacenter_id = eea5d0d7-69e9-44c0-88c5-77f052dc2ff6
                  dhcp = true
                  ip = 10.10.124.225
                  name = loadbalancer
                  nic_id = 5209a504-04c1-49d1-9c71-59cd6fe89fc8

                  Dependencies:
                    profitbricks_datacenter.foobar
                    profitbricks_nic.database_nic
                profitbricks_nic.database_nic:
                  ID = 5209a504-04c1-49d1-9c71-59cd6fe89fc8
                  datacenter_id = eea5d0d7-69e9-44c0-88c5-77f052dc2ff6
                  dhcp = true
                  firewall_active = true
                  ips.# = 1
                  ips.0 = 10.11.212.11
                  lan = 2
                  name = updated
                  server_id = 71ea0a9f-6557-472c-ad20-044a18d44813

                  Dependencies:
                    profitbricks_datacenter.foobar
                    profitbricks_server.webserver
                profitbricks_server.webserver:
                  ID = 71ea0a9f-6557-472c-ad20-044a18d44813
                  availability_zone = ZONE_1
                  boot_volume = ff7591c5-5a5d-4f7f-809a-4b8adcea6a5a
                  cores = 1
                  cpu_family = AMD_OPTERON
                  datacenter_id = eea5d0d7-69e9-44c0-88c5-77f052dc2ff6
                  name = webserver
                  nic.# = 1
                  nic.4050551175.dhcp = true
                  nic.4050551175.firewall.# = 1
                  nic.4050551175.firewall.4236383148.icmp_code =
                  nic.4050551175.firewall.4236383148.icmp_type =
                  nic.4050551175.firewall.4236383148.ip =
                  nic.4050551175.firewall.4236383148.ips.# = 0
                  nic.4050551175.firewall.4236383148.name = SSH
                  nic.4050551175.firewall.4236383148.port_range_end = 22
                  nic.4050551175.firewall.4236383148.port_range_start = 22
                  nic.4050551175.firewall.4236383148.protocol = TCP
                  nic.4050551175.firewall.4236383148.source_ip =
                  nic.4050551175.firewall.4236383148.source_mac =
                  nic.4050551175.firewall.4236383148.target_ip =
                  nic.4050551175.firewall_active = true
                  nic.4050551175.ip =
                  nic.4050551175.ips.# = 1
                  nic.4050551175.ips.0 = 10.13.116.11
                  nic.4050551175.lan = 1
                  nic.4050551175.name =
                  nic.4050551175.nat = false
                  primary_ip = 10.13.116.11
                  primary_nic = 4f8ee05e-d73c-4121-9fc7-63adeae1af39
                  ram = 1024
                  volume.# = 1
                  volume.1751962873.availability_zone =
                  volume.1751962873.bus =
                  volume.1751962873.disk_type = SSD
                  volume.1751962873.image_name = ubuntu-16.04
                  volume.1751962873.image_password = K3tTj8G14a3EgKyNeeiY
                  volume.1751962873.licence_type =
                  volume.1751962873.name = system
                  volume.1751962873.size = 5
                  volume.1751962873.ssh_key_path.# = 0

                  Dependencies:
                    profitbricks_datacenter.foobar
=== RUN   TestAccProfitBricksNic_Basic
--- PASS: TestAccProfitBricksNic_Basic (305.60s)
=== RUN   TestAccProfitBricksServer_Basic
--- PASS: TestAccProfitBricksServer_Basic (260.12s)
=== RUN   TestAccProfitBricksShare_Basic
--- PASS: TestAccProfitBricksShare_Basic (40.00s)
=== RUN   TestAccProfitBricksSnapshot_Basic
--- PASS: TestAccProfitBricksSnapshot_Basic (307.34s)
=== RUN   TestAccProfitBricksUser_Basic
--- PASS: TestAccProfitBricksUser_Basic (168.44s)
=== RUN   TestAccProfitBricksVolume_Basic
--- PASS: TestAccProfitBricksVolume_Basic (320.25s)
FAIL
exit status 1
FAIL    terraform-provider-profitbricks/profitbricks    2464.216s
make: *** [testacc] Error 1
```

### CODE REVIEW

**Comment by jasmingacic** [comment]
@radeksimko I've already reviewed [this](https://github.com/StackPointCloud/terraform-provider-profitbricks/pull/1). This PR addressed what we discussed [here](https://github.com/terraform-providers/terraform-provider-profitbricks/pull/6#issuecomment-319059537). Do you have anything to add?

**Comment by radeksimko** [comment]
Hey @jasmingacic ,
what I can say here is that it's an overwhelmingly big PR 😅. Big enough that I would prefer not to review/merge it until it's split into smaller chunks to allow sane and safe review.

Without looking too deep into the diff I can see the following parts:

 - setting user-agent
 - vendor additions
 - updates for API v4
 - new resource (profitbricks_user)
 - new resource (profitbricks_snapshot)
 - new resource (profitbricks_share)
 - new resource (profitbricks_ipfailover)
 - new resource (profitbricks_group)
 - new data source (profitbricks_snapshot)
 - new data source (profitbricks_resource)

so that's 10 PRs, many of which are IMO independent.

Raising & reviewing smaller PRs is generally a good practice which helps discovering many details (and bugs) you'd otherwise miss in big PRs (with 5k LOC like here). 😉 

I'm more than happy to chime in and read through smaller PRs if you wish.

**Comment by jasmingacic** [comment]
No need for 10 PR but they could be grouped logically. Like vendor update and user agent in one. Snapshot resource and data source in one and respectively with other features. 
@alibazlamit do you mind doing that. Also while doing it could you update terraform in vendors so 0.10.0 is used.

**Comment by jasmingacic** [comment]
@alibazlamit Once you resolve the conflicts the PR will be approved.

**Comment by jasmingacic** [comment]
I'm closing this one since it was split into two PRs

**Pull request closed without merging**
