### PR TITLE
Primary NIC update fix.

### PR DESCRIPTION
**Pull request by jasminSPC**
Fixed how Primary NIC is updated within server

### CODE REVIEW

**Comment by jasminSPC** [comment]
@radeksimko as requested. 

NOTE: Load balancers are failing since the feature is broken with ProfitBricks.
```
=== RUN   TestAccDataSourceDatacenter_matching
--- PASS: TestAccDataSourceDatacenter_matching (14.98s)
=== RUN   TestAccDataSourceImage_basic
--- PASS: TestAccDataSourceImage_basic (4.34s)
=== RUN   TestAccDataSourceLocation_basic
--- PASS: TestAccDataSourceLocation_basic (0.62s)
=== RUN   TestProvider
--- PASS: TestProvider (0.00s)
=== RUN   TestProvider_impl
--- PASS: TestProvider_impl (0.00s)
=== RUN   TestAccProfitBricksDataCenter_Basic
--- PASS: TestAccProfitBricksDataCenter_Basic (13.63s)
=== RUN   TestAccProfitBricksFirewall_Basic
--- PASS: TestAccProfitBricksFirewall_Basic (316.04s)
=== RUN   TestAccProfitBricksIPBlock_Basic
--- PASS: TestAccProfitBricksIPBlock_Basic (1.25s)
=== RUN   TestAccProfitBricksLan_Basic
--- PASS TestAccProfitBricksLan_Basic (34.70s)        
=== RUN   TestAccProfitBricksLoadbalancer_Basic
--- FAIL: TestAccProfitBricksLoadbalancer_Basic (296.10s)
        testing.go:428: Step 0 error: After applying this step, the plan was not empty:
                
                DIFF:
                
                UPDATE: profitbricks_loadbalancer.example
                  ip: "10.11.154.225" => ""
                
                STATE:
                
                profitbricks_datacenter.foobar:
                  ID = 32e6d2db-3d02-4a49-bc81-1d4c1412254d
                  description = 
                  location = us/las
                  name = loadbalancer-test
                profitbricks_loadbalancer.example:
                  ID = 91788171-46c8-40a3-bd09-1fc0dde5d808
                  datacenter_id = 32e6d2db-3d02-4a49-bc81-1d4c1412254d
                  dhcp = true
                  ip = 10.11.154.225
                  name = loadbalancer
                  nic_id = 89789499-bb40-4002-b4d3-0404a240c6d6
                
                  Dependencies:
                    profitbricks_datacenter.foobar
                    profitbricks_nic.database_nic
                profitbricks_nic.database_nic:
                  ID = 89789499-bb40-4002-b4d3-0404a240c6d6
                  datacenter_id = 32e6d2db-3d02-4a49-bc81-1d4c1412254d
                  dhcp = true
                  firewall_active = true
                  ips.# = 1
                  ips.0 = 10.12.226.11
                  lan = 2
                  name = updated
                  server_id = 7b41760d-b7c7-4587-810a-f6f9b524bc09
                
                  Dependencies:
                    profitbricks_datacenter.foobar
                    profitbricks_server.webserver
                profitbricks_server.webserver:
                  ID = 7b41760d-b7c7-4587-810a-f6f9b524bc09
                  availability_zone = ZONE_1
                  boot_volume = 7d533500-b50c-4f97-9040-20fe75da3987
                  cores = 1
                  cpu_family = AMD_OPTERON
                  datacenter_id = 32e6d2db-3d02-4a49-bc81-1d4c1412254d
                  name = webserver
                  nic.# = 1
                  nic.4050551175.dhcp = true
                  nic.4050551175.firewall.# = 1
                  nic.4050551175.firewall.4236383148.icmp_code = 
                  nic.4050551175.firewall.4236383148.icmp_type = 
                  nic.4050551175.firewall.4236383148.ip = 
                  nic.4050551175.firewall.4236383148.ips.# = 0
                  nic.4050551175.firewall.4236383148.name = SSH
                  nic.4050551175.firewall.4236383148.port_range_end = 22
                  nic.4050551175.firewall.4236383148.port_range_start = 22
                  nic.4050551175.firewall.4236383148.protocol = TCP
                  nic.4050551175.firewall.4236383148.source_ip = 
                  nic.4050551175.firewall.4236383148.source_mac = 
                  nic.4050551175.firewall.4236383148.target_ip = 
                  nic.4050551175.firewall_active = true
                  nic.4050551175.ip = 
                  nic.4050551175.ips.# = 1
                  nic.4050551175.ips.0 = 10.13.250.11
                  nic.4050551175.lan = 1
                  nic.4050551175.name = 
                  nic.4050551175.nat = false
                  primary_ip = 10.13.250.11
                  primary_nic = 05e72afd-54a9-47af-8d97-8ac6029ac0f7
                  ram = 1024
                  volume.# = 1
                  volume.1751962873.availability_zone = 
                  volume.1751962873.bus = 
                  volume.1751962873.disk_type = SSD
                  volume.1751962873.image_name = ubuntu-16.04
                  volume.1751962873.image_password = K3tTj8G14a3EgKyNeeiY
                  volume.1751962873.licence_type = 
                  volume.1751962873.name = system
                  volume.1751962873.size = 5
                  volume.1751962873.ssh_key_path.# = 0
                
                  Dependencies:
                    profitbricks_datacenter.foobar
=== RUN   TestAccProfitBricksNic_Basic
--- PASS: TestAccProfitBricksNic_Basic (277.88s)
=== RUN   TestAccProfitBricksServer_Basic
--- PASS: TestAccProfitBricksServer_Basic (228.48s)
=== RUN   TestAccProfitBricksVolume_Basic
--- PASS: TestAccProfitBricksVolume_Basic (267.20s)
```

**Comment by radeksimko** [comment]
Test _results_ are useful, but as discussed via Slack, can you please add a test covering the bugfix? That would presumably go into `profitbricks/resource_profitbricks_server_test.go`

Thanks.

**Comment by jasminSPC** [comment]
@radeksimko I added a secondary NIC to the server test. Before the fix updating server would mess up the secondary NIC.

**Comment by jasminSPC** [comment]
Thanks

**Comment by jasminSPC** [comment]
Just to elaborate the problem a little. When server is provisioned a single public NIC is required which has property `primary_nic`. The way how the `primary_nic` was updated was to grab the first NIC from collection of NICs attached to the server which was causing for another NIC to be updated.

**Pull request merged**
