### PR TITLE
Multiple Updates

### PR DESCRIPTION
**Pull request by pennycoders**
## This PR contains the following changes:
- Updates the provider so that it uses profitbricks-sdk-go v5.0.9 (facilitates future updates)
- Uses/Supports terraform v0.12.21
- Documentation updates
- Uses the new v5 API endpoint
- Uses go v1.13.x for travis-ci and also recommends it for building the provider

### CODE REVIEW

**Comment by pennycoders** [comment]
Hi @jasmingacic 

Could you please take a look at this change when you get a chance? and also, where do I sign up as a maintainer for this provider?

Thanks!
Alex.

**Comment by jasmingacic** [comment]
@pennycoders I no longer have permissions to merge PRs.

**Comment by pennycoders** [comment]
> @pennycoders I no longer have permissions to merge PRs.
> 
> @radeksimko Can you help Alex?

Thanks for the help @jasmingacic !

**Comment by AlexandruGodri** [comment]
Everything looks good!

**Pull request merged**
