### PR TITLE
Snapshot id/name feature

### PR DESCRIPTION
**Pull request by alibazlamit**
This PR addresses the issue here https://github.com/terraform-providers/terraform-provider-profitbricks/issues/3

### CODE REVIEW

**Comment by jasminSPC** [comment]
This is looking good.

@radeksimko We can't add tests for this feature since the provider doesn't have snapshot resource, and even if it had live tests would last for an hour at least. Is this good to go?

**Comment by radeksimko** [comment]
@jasminSPC Up to you. I think it would be nice to have a test for it, but I understand the potential pain. 🤷‍♂️ 

btw. we do have a few acceptance tests in AWS provider which can take an hour to finish.

**Comment by jasminSPC** [comment]
@radeksimko There is an open issue #3 so how about we first close that one and then we add snapshot data source and resource?

**Comment by radeksimko** [comment]
Sounds like a good idea. I'm not so familiar with ProfitBricks - the AWS land has snapshots more-or-less automated and they're separate concept from AMIs (images), so this is kind of confusingly new to me.

I'll defer to your decision here.

**Comment by jasminSPC** [comment]
I'm closing this and with V4 update this snapshot resource and data source will be added.

**Comment by radeksimko** [comment]
btw. I'm not sure the user would ever wanted to run `terraform apply` to create a snapshot, so snapshot resource sounds weird.

From my experience in production environment taking a snapshot is an automated process which takes place at least daily, without human touch. Also snapshots are likely to be around for a long while and that doesn't work well with the Terraform's stateful-approach (i.e. you don't want to keep all snapshot data in the state file I think).

I don't know how people usually solve this in practice with ProfitBricks, but I'm pretty sure that relying on "manual" snapshots done once in a while is a bad idea ™️ .

Snapshot data source however makes total sense.

**Comment by jasminSPC** [comment]
As far as I know ProfitBricks doesn't have that automated users have to create snapshots manually. So in order to test this we would have to have at least one snapshot and since automagical creation of snapshots is not available with PB we need a way to have at least one snapshot in order to test restore. 

I agree it isn't very practical but it is the only way to do it.

**Comment by einyx** [comment]
Sorry guys, I'm chipping in a bit late.
The use case is to create a snapshot with packer to start from a base image that has already few base tools installed and an update kernel.

Unfortunately PB sucks for this kinda of things and snapshotting a packer image is the only way to do it.

**Pull request merged**
